from pathlib import Path

p=Path('source/meshtastic_to_aprs.py'); t=p.read_text(encoding='utf-8')
t=t.replace('meshtastic_to_aprs.py (v7.0.46)','meshtastic_to_aprs.py (v7.0.47)',1)
a='APRSIS_LONG_TEST_MAX_CHARS = max(80, min(450, int(os.getenv("APRSIS_LONG_TEST_MAX_CHARS", "400") or "400")))\n'
assert t.count(a)==1
t=t.replace(a,a+'APRSIS_LONG_BULLETIN_TEST_ENABLED = int(os.getenv("APRSIS_LONG_BULLETIN_TEST_ENABLED", "0") or "0")\n',1)
m='\ndef _aprsis_tnc2_message_line(dst_call: str, text: str, *, with_msgid: bool = True) -> str:\n'; assert t.count(m)==1
fn='''\n\nasync def send_aprsis_long_bulletin_test(text: str, bulletin_number: int = 0) -> dict:\n    """Envía manualmente un BLNx largo solo a APRS-IS, sin tocar RF ni estado automático."""\n    if not bool(APRSIS_LONG_BULLETIN_TEST_ENABLED):\n        return {"ok": True, "sent": False, "reason": "disabled"}\n    if not _aprsis_ready():\n        return {"ok": False, "sent": False, "reason": "aprsis_unavailable"}\n    clean = _aprs_ascii(text).strip()\n    if not clean:\n        return {"ok": False, "sent": False, "reason": "empty_text"}\n    clean = clean[:APRSIS_LONG_TEST_MAX_CHARS]\n    try:\n        number = max(0, min(9, int(bulletin_number)))\n    except Exception:\n        number = 0\n    bulletin = _aprsis_bulletin_name(number)\n    src = (APRSIS_USER or MY_CALL or "").strip().upper()\n    if not src:\n        return {"ok": False, "sent": False, "reason": "missing_source"}\n    dst9 = bulletin[:9].ljust(9, " ")\n    line = f"{src}>APRS,TCPIP*::{dst9}:{clean}"\n    sent = bool(await _aprsis_send_line_safe(line))\n    return {"ok": sent, "sent": sent, "reason": "sent" if sent else "send_failed", "bulletin": bulletin, "chars": len(clean), "text": clean, "line": line}\n'''
t=t.replace(m,fn+m,1)
c='        # --- v7.0.46: diagnóstico manual largo, solo APRS-IS ---\n        if mode == "aprsis_long_test":\n'; assert t.count(c)==1
b='''        # --- v7.0.47: diagnóstico BLNx largo, exclusivamente APRS-IS ---\n        if mode == "aprsis_long_bulletin_test":\n            try:\n                resp = await send_aprsis_long_bulletin_test(obj.get("text", ""), obj.get("bulletin_number", 0))\n            except Exception as exc:\n                resp = {"ok": False, "sent": False, "reason": "internal_error", "error": f"{type(exc).__name__}: {exc}"}\n            try:\n                sock.sendto(json.dumps(resp, ensure_ascii=False).encode("utf-8"), addr)\n            except Exception:\n                pass\n            continue\n\n'''
t=t.replace(c,b+c,1); p.write_text(t,encoding='utf-8',newline='\n')

e=Path('.env_example'); d=e.read_text(encoding='utf-8'); a='APRSIS_LONG_TEST_MAX_CHARS=400\n'; assert d.count(a)==1; e.write_text(d.replace(a,a+'APRSIS_LONG_BULLETIN_TEST_ENABLED=0\n',1),encoding='utf-8',newline='\n')
r=Path('README.md'); r.write_text(r.read_text(encoding='utf-8').replace('v7.0.46','v7.0.47',1),encoding='utf-8',newline='\n')
w=Path('tools/ControlPanel/web_admin.py'); w.write_text(w.read_text(encoding='utf-8').replace('UI 2 · v7.0.46','UI 2 · v7.0.47',1),encoding='utf-8',newline='\n')

test=Path('tests/test_aprsis_long_bulletin_v7047.py')
test.write_text('''import asyncio, importlib.util, os, sys\nfrom pathlib import Path\nfrom unittest import mock\nROOT=Path(__file__).resolve().parents[1]; P=ROOT/"source"/"meshtastic_to_aprs.py"\ndef load():\n os.environ.setdefault("APRSIS_USER","EB2EAS-11"); sys.modules.setdefault("aprslib",mock.MagicMock()); s=importlib.util.spec_from_file_location("gw7047",P); m=importlib.util.module_from_spec(s); sys.modules[s.name]=m; s.loader.exec_module(m); return m\ndef test_disabled():\n m=load(); m.APRSIS_LONG_BULLETIN_TEST_ENABLED=0; x=asyncio.run(m.send_aprsis_long_bulletin_test("PRUEBA "*20,0)); assert not x["sent"] and x["reason"]=="disabled"\ndef test_real_long_bln(monkeypatch):\n m=load(); m.APRSIS_LONG_BULLETIN_TEST_ENABLED=1; m.APRSIS_LONG_TEST_MAX_CHARS=400; m.APRSIS_EMERGENCY_BULLETIN_GROUP=""; monkeypatch.setattr(m,"_aprsis_ready",lambda:True); cap=[]\n async def send(line): cap.append(line); return True\n monkeypatch.setattr(m,"_aprsis_send_line_safe",send); text="PRUEBA BLN LARGO CORTE DE TRAFICO CV-128 km 21.5 CATI URL https://maps.google.com/?q=40.47123,0.02234 FIN-PRUEBA-BLN-LARGO"; assert len(text)>67; x=asyncio.run(m.send_aprsis_long_bulletin_test(text,0)); assert x["sent"] and x["bulletin"]=="BLN0" and x["chars"]==len(text); assert "::BLN0     :" in x["line"] and x["line"].endswith("FIN-PRUEBA-BLN-LARGO") and text in x["line"]\ndef test_group(monkeypatch):\n m=load(); m.APRSIS_LONG_BULLETIN_TEST_ENABLED=1; m.APRSIS_EMERGENCY_BULLETIN_GROUP="EMERG"; monkeypatch.setattr(m,"_aprsis_ready",lambda:True)\n async def send(line): return True\n monkeypatch.setattr(m,"_aprsis_send_line_safe",send); x=asyncio.run(m.send_aprsis_long_bulletin_test("PRUEBA",3)); assert x["bulletin"]=="BLN3EMERG" and "::BLN3EMERG:" in x["line"]\n''',encoding='utf-8',newline='\n')
